name: 'Validation steps'
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  push:
    branches:
      - 'main'

jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:
      - name: Check commit messages start with JIRA numbers or notask
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^(VHERNO-\d*|notask):.*$'
          flags: 'gm'
          error: 'All commits should start with ("VHERNO-XXX:") or "notask:".'
          excludeDescription: 'true'
          excludeTitle: 'true'
          checkAllCommitMessages: 'true'
          accessToken: ${{ secrets.GITHUB_TOKEN }}